import {
	createNodeTekMemoQueue,
	createNodeTekMemoStore,
	readTekMemoNodeRuntimeConfig,
} from "@tekmemo/server/node";

const config = readTekMemoNodeRuntimeConfig();
const store = createNodeTekMemoStore(config);
const queue = createNodeTekMemoQueue(config);

await store.migrate();
if (queue && "migrate" in queue) await queue.migrate();
await store.ensureProject({
	projectId: config.defaultProjectId,
	name: "Default",
});

await store.close();
if (queue && "close" in queue) await queue.close();
console.log(
	`TekMemo self-host bootstrap completed for project '${config.defaultProjectId}'.`,
);
console.log("Set TEKMEMO_API_KEY to a key generated by `pnpm create-api-key`.");
